# Training params
batch_size: 64
epochs: 1000
eval_every_n_epochs: 1
log_every_n_steps: 50
warmup_epochs: 10

# Optimizer params
lr: 0.0004
weight_decay: 10e-6
scheduler_eta_min: 0
scheduler_last_epoch: -1

# Model params
model:
  # Feature extractor
  feature_extractor:
    feature_extractor_name: "resnet50"
  # Projection head
  proj_head:
    proj_head_name: "double_linear"
    feat_dim: 2048
    out_dim: 512


# Dataset params
dataset:
  dataset_name: "coco2014"
  dataset_path: "PATH TO DATASET ROOT"
  s: 1
  input_shape: 224 # Input shape: 3 x 224 x 224
  num_workers: 5
  valid_size: 0.05

# Loss params
loss:
  temperature: 0.5
  use_cosine_similarity: True

# Run params
method: "simclr"
model_name: "SimCLRModel"
outputs_path: "outputs/"
experiment_name: "coco2014"